Repository Devathon-2024-team5/preguntonic_FrontEnd, pull requests merged in 2024-05, with the labels that each got.

#33 Feature/views responsive
  src/app/app.component.html
  src/app/pages/anteroom/anteroom.component.css
  src/app/pages/anteroom/anteroom.component.html
  src/app/pages/game-room/game-room.component.html
  src/app/pages/home/home.component.css
  src/app/pages/home/home.component.html
  src/app/pages/join-room/join-room.component.html
  src/app/pages/results-room/views/final-results/final-results.component.html
  src/app/pages/room-configuration/room-configuration.component.html
  src/app/shared/components/avatar-img/avatar-image.component.css
  src/app/shared/components/avatar-img/avatar-image.component.html
  src/app/shared/components/avatar-img/avatar-image.component.ts
  src/styles/index.css
  src/styles/shared/bootstrap.custom.scss
Labels: style

#34 feat: Add base Readme
  README.md
Labels: documentation

#38 Feature/component change icon button
  src/app/components/change-icon-button/change-icon-button.component.css
  src/app/components/change-icon-button/change-icon-button.component.html
  src/app/components/change-icon-button/change-icon-button.component.spec.ts
  src/app/components/change-icon-button/change-icon-button.component.ts
  src/styles/shared/variables.css
Labels: feature

#39 Feature/component info icon button
  src/app/components/info-icon-button/info-icon-button.component.css
  src/app/components/info-icon-button/info-icon-button.component.html
  src/app/components/info-icon-button/info-icon-button.component.spec.ts
  src/app/components/info-icon-button/info-icon-button.component.ts
Labels: feature

#52 Feature/use custom button in views join and configuration room
  src/app/pages/anteroom/components/code-container/code-container.component.ts
  src/app/pages/join-room/join-room.component.css
  src/app/pages/join-room/join-room.component.html
  src/app/pages/join-room/join-room.component.ts
  src/app/pages/room-configuration/room-configuration.component.css
  src/app/pages/room-configuration/room-configuration.component.html
  src/app/pages/room-configuration/room-configuration.component.ts
Labels: feature

#53 Feature/use exit icon button component
  src/app/components/group-controls/group-controls.component.html
  src/app/components/group-controls/group-controls.component.ts
  src/app/pages/anteroom/components/header-anteroom/header-anteroom.component.html
  src/app/pages/anteroom/components/header-anteroom/header-anteroom.component.ts
  src/app/shared/components/custom-btn/custom-button.component.css
  src/app/shared/components/exit-icon-button/exit-icon-button.component.css
  src/app/shared/components/exit-icon-button/exit-icon-button.component.ts
Labels: feature

#61 Feature/input component
  src/app/shared/components/custon-input/custon-input.component.css
  src/app/shared/components/custon-input/custon-input.component.html
  src/app/shared/components/custon-input/custon-input.component.spec.ts
  src/app/shared/components/custon-input/custon-input.component.ts
  src/app/shared/interfaces/InputConfig.interface.ts
  src/app/shared/types/input.type.ts
  src/styles/shared/utility.css
Labels: feature
